#!/bin/bash
# /etc/init.d/monerod
# version 0.0.1 2018-01-09 (YYYY-MM-DD)
#
### BEGIN INIT INFO
# Provides:   monerod
# Required-Start: $local_fs $remote_fs screen-cleanup
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    Monero Node
# Description:    Starts the monero daemon
### END INIT INFO

# Settings
SERVICE='Monero Node'
USERNAME='root'
ME="$(whoami)"

EXECUTABLE='/opt/monero-v0.11.1.0/monerod'
BLOCK_SYNC_SIZE=10
LOG_FILE='/var/log/xmr.log'
PID_FILE='/var/run/xmr.pid'
STOP_GRACE_TIME=20
KILL_GRACE_TIME=20
DATA_DIR='/opt/monero-db'

as_user() {
	if [ "$ME" == "$USERNAME" ] ; then
		bash -c "$1"
	else
		su - "$USERNAME" -c "$1"
	fi
}

daemon_pid() {
	if [ -f "$PID_FILE" ]; then
		echo $(cat $PID_FILE)
	fi
}

daemon_status() {
	local pid=$(daemon_pid)

	if [ -n "$pid" ]; then
		kill -0 $pid > /dev/null 2>&1
		return $?
	else
		return 1
	fi
}

daemon_start() {
	if daemon_status; then
		echo "$SERVICE is already running (pid: $(daemon_pid))"
	else
		echo "Starting $SERVICE..."
		as_user "$EXECUTABLE --detach --block-sync-size $BLOCK_SYNC_SIZE --log-file $LOG_FILE --pidfile $PID_FILE --data-dir $DATA_DIR"

		sleep 1

		if daemon_status; then
			echo "$SERVICE is running (pid: $(daemon_pid))"
		else
			echo "Failed to start $SERVICE"
		fi
	fi
}

daemon_stop() {
	if daemon_status; then
		echo "Stopping $SERVICE (pid: $(daemon_pid))"
		kill -2 $(daemon_pid)

		sleep $STOP_GRACE_TIME

		if daemon_status; then
			echo "Failed to stop $SERVICE"
		else
			echo "$SERVICE stopped"
		fi
	else
		echo "$SERVICE isn't running"
	fi
}

daemon_kill() {
	if daemon_status; then
		echo "Sending kill signal to $SERVICE (pid: $(daemon_pid))"
		kill -9 $(daemon_pid)

		sleep $KILL_GRACE_TIME

		if daemon_status; then
			echo "Failed to stop $SERVICE"
		else
			echo "$SERVICE stopped"
		fi
	else
		echo "$SERVICE isn't running"
	fi
}

daemon_monitor() {
	tail -f "$LOG_FILE"
}

# Main
case "$1" in
	start)
		daemon_start
	;;
	stop)
		daemon_stop
	;;
	restart)
		daemon_stop
		daemon_start
	;;
	kill)
		daemon_kill
	;;
	monitor)
		daemon_monitor
	;;
	status)
		if daemon_status; then
			echo "$SERVICE is running (pid: $(daemon_pid))"
		else
			echo "$SERVICE isn't running"
		fi
	;;
	*)
		echo "Usage: $0 {start|stop|status|restart|kill|monitor}"
		exit 1
	;;
esac
